(define (problem 15)
(:domain RedCar)
(:objects


 red-car yellow-car yellow-special-car gray-white-car green-car - horizontalCar
 pink-car blue-car orange-car purple-car green-over-car - verticalCar
 purple-truck yellow-truck green-truck - horizontalTruck
 blue-truck - verticalTruck
)
(:init
    (= (x red-car) 0)
(= (y red-car) 2)
(= (x yellow-car) 0)
(= (y yellow-car) 5)
(= (x yellow-special-car) 1)
(= (y yellow-special-car) 4)
(= (x gray-white-car) 3)
(= (y gray-white-car) 3)
(= (x green-car) 1)
(= (y green-car) 0)
(= (x pink-car) 5)
(= (y pink-car) 1)
(= (x blue-car) 4)
(= (y blue-car) 1)
(= (x orange-car) 3)
(= (y orange-car) 1)
(= (x purple-car) 2)
(= (y purple-car) 2)
(= (x green-over-car) 0)
(= (y green-over-car) 3)
(= (x purple-truck) 1)
(= (y purple-truck) 5)
(= (x yellow-truck) 3)
(= (y yellow-truck) 0)
(= (x green-truck) 2)
(= (y green-truck) 5)
(= (x blue-truck) 5)
(= (y blue-truck) 3)
    
    ;; Grid boundaries
    (= (min_x) 0)
    (= (max_x) 6)
    (= (min_y) 0)
    (= (max_y) 6)
    
    ;; Clear cells
    (= (clear 0 0) 1)
(= (clear 1 0) 0)
(= (clear 2 0) 0)
(= (clear 3 0) 0)
(= (clear 4 0) 0)
(= (clear 5 0) 0)
(= (clear 0 1) 1)
(= (clear 1 1) 1)
(= (clear 2 1) 1)
(= (clear 3 1) 0)
(= (clear 4 1) 0)
(= (clear 5 1) 0)
(= (clear 0 2) 0)
(= (clear 1 2) 0)
(= (clear 2 2) 0)
(= (clear 3 2) 0)
(= (clear 4 2) 0)
(= (clear 5 2) 0)
(= (clear 0 3) 0)
(= (clear 1 3) 1)
(= (clear 2 3) 0)
(= (clear 3 3) 0)
(= (clear 4 3) 0)
(= (clear 5 3) 0)
(= (clear 0 4) 0)
(= (clear 1 4) 0)
(= (clear 2 4) 0)
(= (clear 3 4) 1)
(= (clear 4 4) 1)
(= (clear 5 4) 0)
(= (clear 0 5) 0)
(= (clear 1 5) 0)
(= (clear 2 5) 0)
(= (clear 3 5) 0)
(= (clear 4 5) 0)
(= (clear 5 5) 0)
)
(:goal (and 
    (= (x red-car) (- (max_x) 2))
    (= (y red-car) 2)
))
)