(define (problem20)
(:domain RedCar)
(:objects


 red-car orange-car brown-car - horizontalCar
 green-car purple-car green-over-car pink-car blue-sky-car white-gray-car yellow-special-car yellow-over-car - verticalCar
 blue-truck - horizontalTruck
 yellow-truck purple-truck - verticalTruck
)
(:init
    (= (x red-car) 0)
(= (y red-car) 2)
(= (x orange-car) 2)
(= (y orange-car) 0)
(= (x brown-car) 4)
(= (y brown-car) 5)
(= (x green-car) 1)
(= (y green-car) 0)
(= (x purple-car) 2)
(= (y purple-car) 1)
(= (x green-over-car) 3)
(= (y green-over-car) 1)
(= (x pink-car) 5)
(= (y pink-car) 0)
(= (x blue-sky-car) 4)
(= (y blue-sky-car) 0)
(= (x white-gray-car) 4)
(= (y white-gray-car) 2)
(= (x yellow-special-car) 2)
(= (y yellow-special-car) 3)
(= (x yellow-over-car) 3)
(= (y yellow-over-car) 3)
(= (x blue-truck) 1)
(= (y blue-truck) 5)
(= (x yellow-truck) 5)
(= (y yellow-truck) 2)
(= (x purple-truck) 0)
(= (y purple-truck) 3)
    
    ;; Grid boundaries
    (= (min_x) 0)
    (= (max_x) 6)
    (= (min_y) 0)
    (= (max_y) 6)
    
    ;; Clear cells
    (= (clear 0 0) 1)
(= (clear 1 0) 0)
(= (clear 2 0) 0)
(= (clear 3 0) 0)
(= (clear 4 0) 0)
(= (clear 5 0) 0)
(= (clear 0 1) 1)
(= (clear 1 1) 0)
(= (clear 2 1) 0)
(= (clear 3 1) 0)
(= (clear 4 1) 0)
(= (clear 5 1) 0)
(= (clear 0 2) 0)
(= (clear 1 2) 0)
(= (clear 2 2) 0)
(= (clear 3 2) 0)
(= (clear 4 2) 0)
(= (clear 5 2) 0)
(= (clear 0 3) 0)
(= (clear 1 3) 1)
(= (clear 2 3) 0)
(= (clear 3 3) 0)
(= (clear 4 3) 0)
(= (clear 5 3) 0)
(= (clear 0 4) 0)
(= (clear 1 4) 1)
(= (clear 2 4) 0)
(= (clear 3 4) 0)
(= (clear 4 4) 1)
(= (clear 5 4) 0)
(= (clear 0 5) 0)
(= (clear 1 5) 0)
(= (clear 2 5) 0)
(= (clear 3 5) 0)
(= (clear 4 5) 0)
(= (clear 5 5) 0)
)
(:goal (and 
    (= (x red-car) (- (max_x) 2))
    (= (y red-car) 2)
))
)